"""add phone number

Revision ID: 744bef740886
Revises: afd4bf56e902
Create Date: 2023-07-09 21:12:38.700086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744bef740886'
down_revision = 'afd4bf56e902'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
