name : Build and deploy code
on: 
  push:
    branches: 
      - 'main' 
      - 'anotherbranch'
  pull_request:
    branches: 
      - 'main' 
      - 'test_branch'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hi to aakash
        run: echo 'hello aakash'

